export const events = [
   {
      eventName: "100 random acts of kindness",
      startEventDate: "07.20.2024 23:39",
      endEventDate: "07.24.2024 11:20",
      eventVenue: "No 233 Main St. New York, United States",
      eventDescr: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      img: "./images/events/1.jpg",
      imgAlt: "There are two people in costume of angels",
   },
   {
      eventName: "Faith is a process, not a destination",
      startEventDate: "07.20.2024 23:39",
      endEventDate: "07.24.2024 11:20",
      eventVenue: "No 233 Main St. New York, United States",
      eventDescr: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      img: "./images/events/2.jpg",
      imgAlt: "There is the Bible book that stood on special shelf",
   },
   {
      eventName: "there is nothing impossible",
      startEventDate: "07.20.2024 23:39",
      endEventDate: "07.24.2024 11:20",
      eventVenue: "No 233 Main St. New York, United States",
      eventDescr: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      img: "./images/events/2.jpg",
      imgAlt: "There is the Bible book that stood on special shelf",
   },
   {
      eventName: "WATCH AND LISTEN TO OUR SERMONS",
      startEventDate: "07.20.2024 23:39",
      endEventDate: "07.24.2024 11:20",
      eventVenue: "No 233 Main St. New York, United States",
      eventDescr: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      img: "./images/events/1.jpg",
      imgAlt: "There are two people in costume of angels",
   },
];
